language: ruby
before_script:
  - mysql -e 'create database ranked_model_test;'
  - psql -c 'create database ranked_model_test;' -U postgres
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "jruby-19mode"
  - "rbx"
env:
  - "ACTIVERECORD_VERSION=4.1.0.beta1"
  - "ACTIVERECORD_VERSION=4.1.0.beta1 DB=mysql_travis"
  - "ACTIVERECORD_VERSION=4.1.0.beta1 DB=postgresql_travis"
  - "ACTIVERECORD_VERSION=4.0.2"
  - "ACTIVERECORD_VERSION=4.0.2 DB=mysql_travis"
  - "ACTIVERECORD_VERSION=4.0.2 DB=postgresql_travis"
  - "ACTIVERECORD_VERSION=3.2.16"
  - "ACTIVERECORD_VERSION=3.2.16 DB=mysql_travis"
  - "ACTIVERECORD_VERSION=3.2.16 DB=postgresql_travis"
  - "ACTIVERECORD_VERSION=3.1.12"
  - "ACTIVERECORD_VERSION=3.1.12 DB=mysql_travis"
  - "ACTIVERECORD_VERSION=3.1.12 DB=postgresql_travis"
  - "ACTIVERECORD_VERSION=master"
  - "ACTIVERECORD_VERSION=master DB=mysql_travis"
  - "ACTIVERECORD_VERSION=master DB=postgresql_travis"
matrix:
  exclude:
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1 DB=mysql_travis"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1 DB=postgresql_travis"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1"
      rvm: "1.9.3"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1 DB=mysql_travis"
      rvm: "1.9.3"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1 DB=postgresql_travis"
      rvm: "1.9.3"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1 DB=mysql_travis"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1 DB=postgresql_travis"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=master"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=master DB=mysql_travis"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=master DB=postgresql_travis"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=4.0.2"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=4.0.2 DB=mysql_travis"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=4.0.2 DB=postgresql_travis"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=master"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=master DB=mysql_travis"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=master DB=postgresql_travis"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=master"
      rvm: "1.9.3"
    - env: "ACTIVERECORD_VERSION=master DB=mysql_travis"
      rvm: "1.9.3"
    - env: "ACTIVERECORD_VERSION=master DB=postgresql_travis"
      rvm: "1.9.3"
  allow_failures:
    # Master may or may not pass
    - env: "ACTIVERECORD_VERSION=master"
    - env: "ACTIVERECORD_VERSION=master DB=mysql_travis"
    - env: "ACTIVERECORD_VERSION=master DB=postgresql_travis"
    # Rails 3.1 is incompatible with database cleaner 1.2
    - env: "ACTIVERECORD_VERSION=3.1.12 DB=mysql_travis"
    - env: "ACTIVERECORD_VERSION=3.1.12 DB=postgresql_travis"
    # Postgres is not supported before Rails 4.0.
    - env: "ACTIVERECORD_VERSION=3.1.12 DB=postgresql_travis"
    - env: "ACTIVERECORD_VERSION=3.2.16 DB=postgresql_travis"
