language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - mysql -e 'create database ranked_model_test;'
  - psql -c 'create database ranked_model_test;' -U postgres
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9.1.17.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
services:
  - mysql
  - postgresql
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
matrix:
  exclude:
    # Ruby 2.7 uses a `bigdecimal` version that doesn't support BigDecimal.new
    # that Rails 4.2 uses. See also:
    # https://github.com/ruby/bigdecimal#which-version-should-you-select
    - rvm: 2.7
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: jruby-9.1.17.0
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: jruby-9.1.17.0
      gemfile: gemfiles/rails_6_0.gemfile
